# Generated by Django 4.1.3 on 2022-11-08 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=200)),
                ('unidades', models.CharField(max_length=200)),
                ('importe', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('nombre', models.CharField(max_length=200, primary_key='true', serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('modelo', models.CharField(max_length=200, primary_key='true', serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('precio', models.IntegerField()),
                ('unidades', models.IntegerField()),
                ('detalles', models.CharField(max_length=500)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.marca')),
            ],
        ),
    ]
